# -*- coding: utf-8 -*-
"""dataanalysisproject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ocvGQ3b7Dj02c1Ir6abRGcNF5EsPILco
"""

import pandas as pd
import numpy as np

df = pd.DataFrame(pd.read_csv('/content/train.csv'))
df.head()

df['Embarked'].describe()

df.fillna(df.mean(), inplace=True)
df.isnull().sum()

df.corr()
df['FamilySize'] = df['SibSp']+df['Parch']   #make new column family_size by combining these two columns
df.drop(['SibSp','Parch'],axis=1, inplace=True)
df.corr()

df['Alone'] = [0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.head()

df.groupby(['Alone'])['Survived'].mean() #output shows that, if the person is alone he/she has less chance of surviving.

df[['Alone','Fare']].corr() #output shows that, if the person was not alone, the chance the ticket price is higher is high. 

df['Sex'] =[0 if df['Sex'][i]=='male' else 1 for i in df.index] #1 for female 0 for male
df.groupby(['Sex'])['Survived'].mean() #here output shows that , female passengers have more chance of surviving than male ones. i.e,women were prioritized over men.

from google.colab import drive
drive.mount('/content/drive')

"""# New Section"""

from google.colab import files
uploaded = files.upload()